import * as dotenv from 'dotenv';
import * as fs from 'fs';
import * as path from 'path';

dotenv.config();

const TOKEN_FILE = path.resolve(process.cwd(), '.env.tokens');

interface OAuthGroup {
  prefix: string;
  tokenUrl: string;
  clientId: string;
  clientSecret: string;
  scope?: string;
}

interface TokenResponse {
  access_token: string;
  expires_in: number;
}

function detectOAuthGroups(): OAuthGroup[] {
  const env = process.env;
  const prefixes = new Set<string>();

  // Find all env vars ending in _OAUTH_TOKEN_URL, _OAUTH_CLIENT_ID, _OAUTH_CLIENT_SECRET
  for (const key of Object.keys(env)) {
    const match = key.match(/^(.+_|)OAUTH_TOKEN_URL$/);
    if (match) {
      // prefix is everything before OAUTH_ e.g. "BATCHES_" or "" for the default pool
      prefixes.add(match[1]); // e.g. "BATCHES_" | "UAP_" | ""
    }
  }

  const groups: OAuthGroup[] = [];

  for (const prefix of prefixes) {
    const tokenUrl = env[`${prefix}OAUTH_TOKEN_URL`];
    const clientId = env[`${prefix}OAUTH_CLIENT_ID`];
    const clientSecret = env[`${prefix}OAUTH_CLIENT_SECRET`];
    const scope = env[`${prefix}OAUTH_SCOPE`];

    // Validate — all 3 required vars must be present
    const missing: string[] = [];
    if (!tokenUrl)    missing.push(`${prefix}OAUTH_TOKEN_URL`);
    if (!clientId)    missing.push(`${prefix}OAUTH_CLIENT_ID`);
    if (!clientSecret) missing.push(`${prefix}OAUTH_CLIENT_SECRET`);

    if (missing.length > 0 && missing.length < 3) {
      // Partial config — fail loudly
      const present = [`${prefix}OAUTH_TOKEN_URL`, `${prefix}OAUTH_CLIENT_ID`, `${prefix}OAUTH_CLIENT_SECRET`]
        .filter(k => !missing.includes(k))
        .map(k => `  ✓ ${k}`);
      const absent = missing.map(k => `  ✗ ${k}  — MISSING`);
      throw new Error(
        `Incomplete OAuth configuration for prefix "${prefix || 'OAUTH'}":\n` +
        [...present, ...absent].join('\n') +
        '\n\nEither set all 3 vars or remove them all.'
      );
    }

    if (missing.length === 0) {
      groups.push({ prefix: prefix || 'OAUTH', tokenUrl: tokenUrl!, clientId: clientId!, clientSecret: clientSecret!, scope });
    }
  }

  return groups;
}

async function fetchToken(group: OAuthGroup): Promise<string> {
  const params = new URLSearchParams({ grant_type: 'client_credentials' });
  if (group.scope) params.append('scope', group.scope);

  const credentials = Buffer.from(`${group.clientId}:${group.clientSecret}`).toString('base64');

  const response = await fetch(group.tokenUrl, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/x-www-form-urlencoded',
      Authorization: `Basic ${credentials}`,
    },
    body: params.toString(),
  });

  if (!response.ok) {
    const error = await response.text();
    throw new Error(`OAuth2 token fetch failed for "${group.prefix}" [${response.status}]: ${error}`);
  }

  const data = (await response.json()) as TokenResponse;
  return data.access_token;
}

export default async function globalSetup(): Promise<void> {
  const groups = detectOAuthGroups();

  if (groups.length === 0) {
    console.log('[globalSetup] No OAuth groups found — skipping token pre-fetch.');
    return;
  }

  console.log(`[globalSetup] Fetching tokens for: ${groups.map(g => g.prefix).join(', ')}`);

  const lines: string[] = ['# Auto-generated by globalSetup — do not commit', ''];

  for (const group of groups) {
    const token = await fetchToken(group);
    // Store as <PREFIX>_TOKEN (e.g. OAUTH_TOKEN, BATCHES_OAUTH_TOKEN, UAP_OAUTH_TOKEN)
    const envKey = group.prefix === 'OAUTH' ? 'OAUTH_TOKEN' : `${group.prefix}OAUTH_TOKEN`;
    lines.push(`${envKey}=${token}`);
    console.log(`[globalSetup] ✓ ${envKey} fetched`);
  }

  fs.writeFileSync(TOKEN_FILE, lines.join('\n'), 'utf8');
  console.log(`[globalSetup] Tokens written to ${TOKEN_FILE}`);
}
